[package]
name = "tv_emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
mp4 = "0.12.0"
mp4parse = "0.12.0"
rand = "0.8.5"
